# Generated by Django 4.1 on 2022-09-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aakarapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="TaskZero",),
    ]
