# Generated by Django 4.1 on 2022-09-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aakarapp", "0002_delete_taskzero"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskZero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crid", models.CharField(max_length=10)),
                ("firstName", models.CharField(max_length=200)),
                ("lasttName", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=10)),
            ],
        ),
    ]
