# Generated by Django 3.2.5 on 2022-09-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aakarapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskZero',
        ),
    ]
