# Generated by Django 4.1 on 2022-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aakarapp", "0005_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crid", models.CharField(max_length=10)),
                ("username", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="aakarapp/images")),
            ],
        ),
        migrations.AlterField(
            model_name="taskzero", name="pincode", field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="taskzero",
            name="whatsappNo",
            field=models.CharField(max_length=10),
        ),
    ]
