# Generated by Django 4.1 on 2022-09-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aakarapp", "0006_taskone_alter_taskzero_pincode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskone",
            name="marks",
            field=models.CharField(default="", max_length=200),
        ),
    ]
