# Generated by Django 4.1 on 2022-11-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakarapp', '0007_taskone_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskone',
            name='image',
        ),
        migrations.AddField(
            model_name='taskone',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskone',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskone',
            name='crid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='taskone',
            name='marks',
            field=models.CharField(max_length=100),
        ),
    ]
