# Generated by Django 4.1 on 2023-01-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakarapp', '0012_taskfour'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crid', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('link', models.TextField()),
                ('marks', models.CharField(max_length=100)),
            ],
        ),
    ]
