# Generated by Django 4.1 on 2023-10-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aakarapp", "0016_taskeight"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskzero",
            name="name",
            field=models.CharField(default="Enter your name here", max_length=200),
            preserve_default=False,
        ),
    ]
