# Generated by Django 4.1 on 2023-10-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aakarapp", "0018_alter_taskzero_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskzero",
            name="name",
        ),
        migrations.AddField(
            model_name="taskzero",
            name="names",
            field=models.CharField(default="Name", max_length=200),
            preserve_default=False,
        ),
    ]
