# Generated by Django 4.1 on 2023-10-25 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aakarapp", "0019_remove_taskzero_name_taskzero_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskzero",
            name="names",
        ),
    ]
