# Generated by Django 4.1 on 2023-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aakarapp", "0020_remove_taskzero_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskzero",
            name="names",
            field=models.CharField(default="Name not entered", max_length=200),
        ),
    ]
