# Generated by Django 4.1 on 2023-10-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aakarapp", "0021_taskzero_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskzero",
            name="names",
            field=models.CharField(max_length=200),
        ),
    ]
