# Generated by Django 4.1 on 2023-10-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aakarapp", "0022_alter_taskzero_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskzero",
            name="email",
            field=models.CharField(
                default="Enter your email-address (HIGH PRIORITY)", max_length=200
            ),
            preserve_default=False,
        ),
    ]
