# Generated by Django 4.1 on 2023-10-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aakarapp", "0024_remove_taskzero_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskzero",
            name="email",
            field=models.CharField(default="Automatic email", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskzero",
            name="emails",
            field=models.CharField(
                default="Update your profile to add registered email address",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
