# Generated by Django 5.2.5 on 2025-09-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aakarapp", "0025_taskzero_email_taskzero_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskzero",
            name="city",
            field=models.CharField(default="", max_length=200),
        ),
    ]
