# Generated by Django 5.2.5 on 2025-09-05 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aakarapp", "0026_taskzero_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="submissions/"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("marks", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("points", models.IntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name="email_auto",
        ),
        migrations.DeleteModel(
            name="taskEight",
        ),
        migrations.DeleteModel(
            name="taskFive",
        ),
        migrations.DeleteModel(
            name="taskFour",
        ),
        migrations.DeleteModel(
            name="TaskOne",
        ),
        migrations.DeleteModel(
            name="taskSeven",
        ),
        migrations.DeleteModel(
            name="taskSix",
        ),
        migrations.DeleteModel(
            name="taskThree",
        ),
        migrations.DeleteModel(
            name="taskTwo",
        ),
        migrations.AddField(
            model_name="submission",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="aakarapp.task"
            ),
        ),
    ]
