# Generated by Django 5.2.5 on 2025-09-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aakarapp",
            "0027_submission_task_delete_email_auto_delete_taskeight_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: The task will disappear after this date.",
                null=True,
            ),
        ),
    ]
