# Generated by Django 5.2.5 on 2025-09-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aakarapp", "0028_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="graded",
            field=models.BooleanField(default=False),
        ),
    ]
