# Generated by Django 5.2.5 on 2025-09-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aakarapp", "0029_submission_graded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskzero",
            name="address",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="taskzero",
            name="dept",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
