# Generated by Django 5.2.5 on 2025-09-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aakarapp", "0030_alter_taskzero_address_alter_taskzero_dept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskzero",
            name="address",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="taskzero",
            name="dept",
            field=models.CharField(max_length=200),
        ),
    ]
